# Generated by Django 6.0.3 on 2026-03-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie_balance',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
