# Generated by Django 4.2.7 on 2026-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sellerprofile_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
