# Generated by Django 6.0.3 on 2026-03-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_add_category_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('products_viewed', models.PositiveIntegerField(default=0)),
                ('searches_made', models.PositiveIntegerField(default=0)),
                ('items_added_to_cart', models.PositiveIntegerField(default=0)),
                ('purchases_made', models.PositiveIntegerField(default=0)),
                ('total_scroll_depth', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('entry_point', models.URLField(max_length=500)),
                ('exit_point', models.URLField(blank=True, max_length=500)),
                ('conversion_goal', models.CharField(blank=True, max_length=100)),
                ('goal_completed', models.BooleanField(default=False)),
                ('steps', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('click_x', models.IntegerField()),
                ('click_y', models.IntegerField()),
                ('viewport_width', models.IntegerField()),
                ('viewport_height', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['page_url', 'timestamp'], name='analytics_h_page_ur_ee8de9_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_h_user_id_2fd6e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('action_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('button_click', 'Button Click'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('scroll', 'Scroll Behavior'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=50)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('element_selector', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_on_page', models.PositiveIntegerField(default=0)),
                ('scroll_depth', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_708804_idx'), models.Index(fields=['session_id', 'timestamp'], name='analytics_u_session_dec61c_idx'), models.Index(fields=['action_type', 'timestamp'], name='analytics_u_action__57c867_idx'), models.Index(fields=['product', 'timestamp'], name='analytics_u_product_d6d04a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'start_time'], name='analytics_u_user_id_4a09ce_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='analytics_u_session_1131bd_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['user', 'start_time'], name='analytics_u_user_id_8bd1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['session', 'start_time'], name='analytics_u_session_19090f_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['goal_completed'], name='analytics_u_goal_co_63e904_idx'),
        ),
    ]
