# Generated by Django 6.0.3 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_seller_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller_phone',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
