# Generated by Django 4.2.7 on 2026-03-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Store image as binary data in PostgreSQL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Original image URL reference', max_length=500, null=True),
        ),
    ]
