# Generated by Django 4.2.7 on 2026-03-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_gameplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplay',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
