# Generated by Django 6.0.3 on 2026-03-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_add_category_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_preferences', models.JSONField(default=dict, help_text='Category ID -> preference weight (0-1)')),
                ('favorite_flavors', models.JSONField(default=list, help_text='List of favorite flavor tags')),
                ('disliked_flavors', models.JSONField(default=list, help_text='List of disliked flavor tags')),
                ('dietary_restrictions', models.JSONField(default=list, help_text='List of dietary restrictions')),
                ('preferred_ingredients', models.JSONField(default=list, help_text='List of preferred ingredients')),
                ('price_sensitivity', models.FloatField(default=0.5, help_text='0=price insensitive, 1=very price sensitive')),
                ('novelty_seeking', models.FloatField(default=0.5, help_text='0=conservative, 1=loves new things')),
                ('brand_loyalty', models.FloatField(default=0.5, help_text='0=not loyal, 1=very loyal')),
                ('preferred_order_times', models.JSONField(default=list, help_text='Preferred hours for ordering')),
                ('seasonal_preferences', models.JSONField(default=dict, help_text='Season -> category preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(help_text='Algorithm that generated this recommendation', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1)')),
                ('reason', models.TextField(blank=True, help_text='Why this was recommended')),
                ('is_active', models.BooleanField(default=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('not_interested', 'Not Interested'), ('already_purchased', 'Already Purchased'), ('not_relevant', 'Not Relevant')], max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating if applicable', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendation_system.userrecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Unique cache key', max_length=255)),
                ('algorithm', models.CharField(max_length=50)),
                ('product_data', models.JSONField(help_text='Cached product recommendations')),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'algorithm'], name='recommendat_user_id_1c4a67_idx'), models.Index(fields=['cache_key'], name='recommendat_cache_k_8fae84_idx'), models.Index(fields=['expires_at'], name='recommendat_expires_0e0749_idx')],
                'unique_together': {('user', 'cache_key')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='viewed, clicked, purchased, feedback', max_length=20)),
                ('product_ids', models.JSONField(help_text='List of product IDs involved')),
                ('algorithm', models.CharField(blank=True, max_length=50)),
                ('context', models.JSONField(default=dict, help_text='Additional context like time, device, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_46af3f_idx'), models.Index(fields=['action_type', 'created_at'], name='recommendat_action__5cf18a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('trending_score', models.FloatField(default=0, help_text='Overall trending score')),
                ('velocity_score', models.FloatField(default=0, help_text='Rate of increase')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_data', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'period_start'], name='recommendat_period_c33123_idx'), models.Index(fields=['trending_score'], name='recommendat_trendin_f31906_idx'), models.Index(fields=['velocity_score'], name='recommendat_velocit_e800b3_idx')],
                'unique_together': {('product', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('review', 'Review'), ('share', 'Share'), ('wishlist', 'Add to Wishlist')], max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds for views', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviors', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'behavior_type', 'created_at'], name='recommendat_user_id_b6f9d2_idx'), models.Index(fields=['product', 'behavior_type'], name='recommendat_product_fb913a_idx'), models.Index(fields=['created_at'], name='recommendat_created_65499c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_ffa897_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'is_active'], name='recommendat_user_id_5fa97a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['algorithm', 'created_at'], name='recommendat_algorit_797e40_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['user', 'feedback_type'], name='recommendat_user_id_544e56_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['feedback_type', 'created_at'], name='recommendat_feedbac_d3b01e_idx'),
        ),
    ]
