# Generated by Django 6.0.3 on 2026-03-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='action_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('home_page_view', 'Home Page View'), ('about_page_view', 'About Page View'), ('contact_page_view', 'Contact Page View'), ('selling_page_view', 'Selling Page View'), ('purchase_page_view', 'Purchase Page View'), ('product_view', 'Product View'), ('button_click', 'Button Click'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('scroll', 'Scroll Behavior'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=50),
        ),
    ]
