# Generated by Django 4.2.7 on 2026-03-15 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('scratch_card', 'Scratch Card'), ('memory_match', 'Memory Match'), ('spin_wheel', 'Spin the Wheel')], max_length=20)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
