# Generated by Django 4.2.7 on 2026-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_sellerprofile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
