# Generated by Django 6.0.3 on 2026-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
