# Generated by Django 6.0.3 on 2026-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller_address_product_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
